### ISSUE TITLE
Add css rule for hiding

### ISSUE THREAD

**Issue by Naramsim** [balde73/creativeGo#3]
Add a rule like

```
.hidden {
display:none;
}
```

and another one for resetting it(initial)

**Comment by balde73** [comment]
For general case you can use the "hide" class

```
.hide{
   display: none;      
}
```

Then you can remove the hide class in javascript.

Also, if you want to hide something only when the screen is smaller than 620px you can use "no-mob", or "only-mob" for the opposite case.
